# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonathan/FighterPilot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonathan/FighterPilot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/FighterPilot/CMakeFiles /home/jonathan/FighterPilot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/FighterPilot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FighterPilot

# Build rule for target.
FighterPilot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FighterPilot
.PHONY : FighterPilot

# fast build rule for target.
FighterPilot/fast:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/build
.PHONY : FighterPilot/fast

aaGun.o: aaGun.cpp.o
.PHONY : aaGun.o

# target to build an object file
aaGun.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/aaGun.cpp.o
.PHONY : aaGun.cpp.o

aaGun.i: aaGun.cpp.i
.PHONY : aaGun.i

# target to preprocess a source file
aaGun.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/aaGun.cpp.i
.PHONY : aaGun.cpp.i

aaGun.s: aaGun.cpp.s
.PHONY : aaGun.s

# target to generate assembly for a file
aaGun.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/aaGun.cpp.s
.PHONY : aaGun.cpp.s

angle.o: angle.cpp.o
.PHONY : angle.o

# target to build an object file
angle.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/angle.cpp.o
.PHONY : angle.cpp.o

angle.i: angle.cpp.i
.PHONY : angle.i

# target to preprocess a source file
angle.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/angle.cpp.i
.PHONY : angle.cpp.i

angle.s: angle.cpp.s
.PHONY : angle.s

# target to generate assembly for a file
angle.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/angle.cpp.s
.PHONY : angle.cpp.s

assetLoader.o: assetLoader.cpp.o
.PHONY : assetLoader.o

# target to build an object file
assetLoader.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/assetLoader.cpp.o
.PHONY : assetLoader.cpp.o

assetLoader.i: assetLoader.cpp.i
.PHONY : assetLoader.i

# target to preprocess a source file
assetLoader.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/assetLoader.cpp.i
.PHONY : assetLoader.cpp.i

assetLoader.s: assetLoader.cpp.s
.PHONY : assetLoader.s

# target to generate assembly for a file
assetLoader.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/assetLoader.cpp.s
.PHONY : assetLoader.cpp.s

blackSmoke.o: blackSmoke.cpp.o
.PHONY : blackSmoke.o

# target to build an object file
blackSmoke.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/blackSmoke.cpp.o
.PHONY : blackSmoke.cpp.o

blackSmoke.i: blackSmoke.cpp.i
.PHONY : blackSmoke.i

# target to preprocess a source file
blackSmoke.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/blackSmoke.cpp.i
.PHONY : blackSmoke.cpp.i

blackSmoke.s: blackSmoke.cpp.s
.PHONY : blackSmoke.s

# target to generate assembly for a file
blackSmoke.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/blackSmoke.cpp.s
.PHONY : blackSmoke.cpp.s

bomb.o: bomb.cpp.o
.PHONY : bomb.o

# target to build an object file
bomb.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bomb.cpp.o
.PHONY : bomb.cpp.o

bomb.i: bomb.cpp.i
.PHONY : bomb.i

# target to preprocess a source file
bomb.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bomb.cpp.i
.PHONY : bomb.cpp.i

bomb.s: bomb.cpp.s
.PHONY : bomb.s

# target to generate assembly for a file
bomb.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bomb.cpp.s
.PHONY : bomb.cpp.s

bullet.o: bullet.cpp.o
.PHONY : bullet.o

# target to build an object file
bullet.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bullet.cpp.o
.PHONY : bullet.cpp.o

bullet.i: bullet.cpp.i
.PHONY : bullet.i

# target to preprocess a source file
bullet.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bullet.cpp.i
.PHONY : bullet.cpp.i

bullet.s: bullet.cpp.s
.PHONY : bullet.s

# target to generate assembly for a file
bullet.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bullet.cpp.s
.PHONY : bullet.cpp.s

bulletEffect.o: bulletEffect.cpp.o
.PHONY : bulletEffect.o

# target to build an object file
bulletEffect.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bulletEffect.cpp.o
.PHONY : bulletEffect.cpp.o

bulletEffect.i: bulletEffect.cpp.i
.PHONY : bulletEffect.i

# target to preprocess a source file
bulletEffect.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bulletEffect.cpp.i
.PHONY : bulletEffect.cpp.i

bulletEffect.s: bulletEffect.cpp.s
.PHONY : bulletEffect.s

# target to generate assembly for a file
bulletEffect.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/bulletEffect.cpp.s
.PHONY : bulletEffect.cpp.s

campaign.o: campaign.cpp.o
.PHONY : campaign.o

# target to build an object file
campaign.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/campaign.cpp.o
.PHONY : campaign.cpp.o

campaign.i: campaign.cpp.i
.PHONY : campaign.i

# target to preprocess a source file
campaign.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/campaign.cpp.i
.PHONY : campaign.cpp.i

campaign.s: campaign.cpp.s
.PHONY : campaign.s

# target to generate assembly for a file
campaign.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/campaign.cpp.s
.PHONY : campaign.cpp.s

collide.o: collide.cpp.o
.PHONY : collide.o

# target to build an object file
collide.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/collide.cpp.o
.PHONY : collide.cpp.o

collide.i: collide.cpp.i
.PHONY : collide.i

# target to preprocess a source file
collide.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/collide.cpp.i
.PHONY : collide.cpp.i

collide.s: collide.cpp.s
.PHONY : collide.s

# target to generate assembly for a file
collide.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/collide.cpp.s
.PHONY : collide.cpp.s

contrail.o: contrail.cpp.o
.PHONY : contrail.o

# target to build an object file
contrail.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrail.cpp.o
.PHONY : contrail.cpp.o

contrail.i: contrail.cpp.i
.PHONY : contrail.i

# target to preprocess a source file
contrail.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrail.cpp.i
.PHONY : contrail.cpp.i

contrail.s: contrail.cpp.s
.PHONY : contrail.s

# target to generate assembly for a file
contrail.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrail.cpp.s
.PHONY : contrail.cpp.s

contrailSmall.o: contrailSmall.cpp.o
.PHONY : contrailSmall.o

# target to build an object file
contrailSmall.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrailSmall.cpp.o
.PHONY : contrailSmall.cpp.o

contrailSmall.i: contrailSmall.cpp.i
.PHONY : contrailSmall.i

# target to preprocess a source file
contrailSmall.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrailSmall.cpp.i
.PHONY : contrailSmall.cpp.i

contrailSmall.s: contrailSmall.cpp.s
.PHONY : contrailSmall.s

# target to generate assembly for a file
contrailSmall.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/contrailSmall.cpp.s
.PHONY : contrailSmall.cpp.s

controlManager.o: controlManager.cpp.o
.PHONY : controlManager.o

# target to build an object file
controlManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/controlManager.cpp.o
.PHONY : controlManager.cpp.o

controlManager.i: controlManager.cpp.i
.PHONY : controlManager.i

# target to preprocess a source file
controlManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/controlManager.cpp.i
.PHONY : controlManager.cpp.i

controlManager.s: controlManager.cpp.s
.PHONY : controlManager.s

# target to generate assembly for a file
controlManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/controlManager.cpp.s
.PHONY : controlManager.cpp.s

dataManager.o: dataManager.cpp.o
.PHONY : dataManager.o

# target to build an object file
dataManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dataManager.cpp.o
.PHONY : dataManager.cpp.o

dataManager.i: dataManager.cpp.i
.PHONY : dataManager.i

# target to preprocess a source file
dataManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dataManager.cpp.i
.PHONY : dataManager.cpp.i

dataManager.s: dataManager.cpp.s
.PHONY : dataManager.s

# target to generate assembly for a file
dataManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dataManager.cpp.s
.PHONY : dataManager.cpp.s

debrisSmokeTrail.o: debrisSmokeTrail.cpp.o
.PHONY : debrisSmokeTrail.o

# target to build an object file
debrisSmokeTrail.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debrisSmokeTrail.cpp.o
.PHONY : debrisSmokeTrail.cpp.o

debrisSmokeTrail.i: debrisSmokeTrail.cpp.i
.PHONY : debrisSmokeTrail.i

# target to preprocess a source file
debrisSmokeTrail.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debrisSmokeTrail.cpp.i
.PHONY : debrisSmokeTrail.cpp.i

debrisSmokeTrail.s: debrisSmokeTrail.cpp.s
.PHONY : debrisSmokeTrail.s

# target to generate assembly for a file
debrisSmokeTrail.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debrisSmokeTrail.cpp.s
.PHONY : debrisSmokeTrail.cpp.s

debugBreak.o: debugBreak.cpp.o
.PHONY : debugBreak.o

# target to build an object file
debugBreak.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debugBreak.cpp.o
.PHONY : debugBreak.cpp.o

debugBreak.i: debugBreak.cpp.i
.PHONY : debugBreak.i

# target to preprocess a source file
debugBreak.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debugBreak.cpp.i
.PHONY : debugBreak.cpp.i

debugBreak.s: debugBreak.cpp.s
.PHONY : debugBreak.s

# target to generate assembly for a file
debugBreak.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/debugBreak.cpp.s
.PHONY : debugBreak.cpp.s

definitions.o: definitions.cpp.o
.PHONY : definitions.o

# target to build an object file
definitions.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/definitions.cpp.o
.PHONY : definitions.cpp.o

definitions.i: definitions.cpp.i
.PHONY : definitions.i

# target to preprocess a source file
definitions.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/definitions.cpp.i
.PHONY : definitions.cpp.i

definitions.s: definitions.cpp.s
.PHONY : definitions.s

# target to generate assembly for a file
definitions.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/definitions.cpp.s
.PHONY : definitions.cpp.s

dogFight.o: dogFight.cpp.o
.PHONY : dogFight.o

# target to build an object file
dogFight.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dogFight.cpp.o
.PHONY : dogFight.cpp.o

dogFight.i: dogFight.cpp.i
.PHONY : dogFight.i

# target to preprocess a source file
dogFight.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dogFight.cpp.i
.PHONY : dogFight.cpp.i

dogFight.s: dogFight.cpp.s
.PHONY : dogFight.s

# target to generate assembly for a file
dogFight.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/dogFight.cpp.s
.PHONY : dogFight.cpp.s

engine.o: engine.cpp.o
.PHONY : engine.o

# target to build an object file
engine.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/engine.cpp.o
.PHONY : engine.cpp.o

engine.i: engine.cpp.i
.PHONY : engine.i

# target to preprocess a source file
engine.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/engine.cpp.i
.PHONY : engine.cpp.i

engine.s: engine.cpp.s
.PHONY : engine.s

# target to generate assembly for a file
engine.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/engine.cpp.s
.PHONY : engine.cpp.s

ephemeris.o: ephemeris.cpp.o
.PHONY : ephemeris.o

# target to build an object file
ephemeris.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ephemeris.cpp.o
.PHONY : ephemeris.cpp.o

ephemeris.i: ephemeris.cpp.i
.PHONY : ephemeris.i

# target to preprocess a source file
ephemeris.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ephemeris.cpp.i
.PHONY : ephemeris.cpp.i

ephemeris.s: ephemeris.cpp.s
.PHONY : ephemeris.s

# target to generate assembly for a file
ephemeris.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ephemeris.cpp.s
.PHONY : ephemeris.cpp.s

explosionFlash.o: explosionFlash.cpp.o
.PHONY : explosionFlash.o

# target to build an object file
explosionFlash.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash.cpp.o
.PHONY : explosionFlash.cpp.o

explosionFlash.i: explosionFlash.cpp.i
.PHONY : explosionFlash.i

# target to preprocess a source file
explosionFlash.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash.cpp.i
.PHONY : explosionFlash.cpp.i

explosionFlash.s: explosionFlash.cpp.s
.PHONY : explosionFlash.s

# target to generate assembly for a file
explosionFlash.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash.cpp.s
.PHONY : explosionFlash.cpp.s

explosionFlash2.o: explosionFlash2.cpp.o
.PHONY : explosionFlash2.o

# target to build an object file
explosionFlash2.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash2.cpp.o
.PHONY : explosionFlash2.cpp.o

explosionFlash2.i: explosionFlash2.cpp.i
.PHONY : explosionFlash2.i

# target to preprocess a source file
explosionFlash2.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash2.cpp.i
.PHONY : explosionFlash2.cpp.i

explosionFlash2.s: explosionFlash2.cpp.s
.PHONY : explosionFlash2.s

# target to generate assembly for a file
explosionFlash2.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionFlash2.cpp.s
.PHONY : explosionFlash2.cpp.s

explosionSmoke.o: explosionSmoke.cpp.o
.PHONY : explosionSmoke.o

# target to build an object file
explosionSmoke.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSmoke.cpp.o
.PHONY : explosionSmoke.cpp.o

explosionSmoke.i: explosionSmoke.cpp.i
.PHONY : explosionSmoke.i

# target to preprocess a source file
explosionSmoke.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSmoke.cpp.i
.PHONY : explosionSmoke.cpp.i

explosionSmoke.s: explosionSmoke.cpp.s
.PHONY : explosionSmoke.s

# target to generate assembly for a file
explosionSmoke.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSmoke.cpp.s
.PHONY : explosionSmoke.cpp.s

explosionSparks.o: explosionSparks.cpp.o
.PHONY : explosionSparks.o

# target to build an object file
explosionSparks.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSparks.cpp.o
.PHONY : explosionSparks.cpp.o

explosionSparks.i: explosionSparks.cpp.i
.PHONY : explosionSparks.i

# target to preprocess a source file
explosionSparks.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSparks.cpp.i
.PHONY : explosionSparks.cpp.i

explosionSparks.s: explosionSparks.cpp.s
.PHONY : explosionSparks.s

# target to generate assembly for a file
explosionSparks.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/explosionSparks.cpp.s
.PHONY : explosionSparks.cpp.s

fileManager.o: fileManager.cpp.o
.PHONY : fileManager.o

# target to build an object file
fileManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fileManager.cpp.o
.PHONY : fileManager.cpp.o

fileManager.i: fileManager.cpp.i
.PHONY : fileManager.i

# target to preprocess a source file
fileManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fileManager.cpp.i
.PHONY : fileManager.cpp.i

fileManager.s: fileManager.cpp.s
.PHONY : fileManager.s

# target to generate assembly for a file
fileManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fileManager.cpp.s
.PHONY : fileManager.cpp.s

fireball.o: fireball.cpp.o
.PHONY : fireball.o

# target to build an object file
fireball.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fireball.cpp.o
.PHONY : fireball.cpp.o

fireball.i: fireball.cpp.i
.PHONY : fireball.i

# target to preprocess a source file
fireball.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fireball.cpp.i
.PHONY : fireball.cpp.i

fireball.s: fireball.cpp.s
.PHONY : fireball.s

# target to generate assembly for a file
fireball.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/fireball.cpp.s
.PHONY : fireball.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/game.cpp.s
.PHONY : game.cpp.s

glew.o: glew.c.o
.PHONY : glew.o

# target to build an object file
glew.c.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/glew.c.o
.PHONY : glew.c.o

glew.i: glew.c.i
.PHONY : glew.i

# target to preprocess a source file
glew.c.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/glew.c.i
.PHONY : glew.c.i

glew.s: glew.c.s
.PHONY : glew.s

# target to generate assembly for a file
glew.c.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/glew.c.s
.PHONY : glew.c.s

graphicsManager.o: graphicsManager.cpp.o
.PHONY : graphicsManager.o

# target to build an object file
graphicsManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/graphicsManager.cpp.o
.PHONY : graphicsManager.cpp.o

graphicsManager.i: graphicsManager.cpp.i
.PHONY : graphicsManager.i

# target to preprocess a source file
graphicsManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/graphicsManager.cpp.i
.PHONY : graphicsManager.cpp.i

graphicsManager.s: graphicsManager.cpp.s
.PHONY : graphicsManager.s

# target to generate assembly for a file
graphicsManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/graphicsManager.cpp.s
.PHONY : graphicsManager.cpp.s

groundExplosionFlash.o: groundExplosionFlash.cpp.o
.PHONY : groundExplosionFlash.o

# target to build an object file
groundExplosionFlash.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/groundExplosionFlash.cpp.o
.PHONY : groundExplosionFlash.cpp.o

groundExplosionFlash.i: groundExplosionFlash.cpp.i
.PHONY : groundExplosionFlash.i

# target to preprocess a source file
groundExplosionFlash.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/groundExplosionFlash.cpp.i
.PHONY : groundExplosionFlash.cpp.i

groundExplosionFlash.s: groundExplosionFlash.cpp.s
.PHONY : groundExplosionFlash.s

# target to generate assembly for a file
groundExplosionFlash.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/groundExplosionFlash.cpp.s
.PHONY : groundExplosionFlash.cpp.s

input.o: input.cpp.o
.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i
.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s
.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/input.cpp.s
.PHONY : input.cpp.s

level.o: level.cpp.o
.PHONY : level.o

# target to build an object file
level.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/level.cpp.o
.PHONY : level.cpp.o

level.i: level.cpp.i
.PHONY : level.i

# target to preprocess a source file
level.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/level.cpp.i
.PHONY : level.cpp.i

level.s: level.cpp.s
.PHONY : level.s

# target to generate assembly for a file
level.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/level.cpp.s
.PHONY : level.cpp.s

levelEditor.o: levelEditor.cpp.o
.PHONY : levelEditor.o

# target to build an object file
levelEditor.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/levelEditor.cpp.o
.PHONY : levelEditor.cpp.o

levelEditor.i: levelEditor.cpp.i
.PHONY : levelEditor.i

# target to preprocess a source file
levelEditor.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/levelEditor.cpp.i
.PHONY : levelEditor.cpp.i

levelEditor.s: levelEditor.cpp.s
.PHONY : levelEditor.s

# target to generate assembly for a file
levelEditor.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/levelEditor.cpp.s
.PHONY : levelEditor.cpp.s

menuScreen.o: menuScreen.cpp.o
.PHONY : menuScreen.o

# target to build an object file
menuScreen.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menuScreen.cpp.o
.PHONY : menuScreen.cpp.o

menuScreen.i: menuScreen.cpp.i
.PHONY : menuScreen.i

# target to preprocess a source file
menuScreen.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menuScreen.cpp.i
.PHONY : menuScreen.cpp.i

menuScreen.s: menuScreen.cpp.s
.PHONY : menuScreen.s

# target to generate assembly for a file
menuScreen.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menuScreen.cpp.s
.PHONY : menuScreen.cpp.s

menus.o: menus.cpp.o
.PHONY : menus.o

# target to build an object file
menus.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menus.cpp.o
.PHONY : menus.cpp.o

menus.i: menus.cpp.i
.PHONY : menus.i

# target to preprocess a source file
menus.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menus.cpp.i
.PHONY : menus.cpp.i

menus.s: menus.cpp.s
.PHONY : menus.s

# target to generate assembly for a file
menus.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/menus.cpp.s
.PHONY : menus.cpp.s

missile.o: missile.cpp.o
.PHONY : missile.o

# target to build an object file
missile.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/missile.cpp.o
.PHONY : missile.cpp.o

missile.i: missile.cpp.i
.PHONY : missile.i

# target to preprocess a source file
missile.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/missile.cpp.i
.PHONY : missile.cpp.i

missile.s: missile.cpp.s
.PHONY : missile.s

# target to generate assembly for a file
missile.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/missile.cpp.s
.PHONY : missile.cpp.s

object.o: object.cpp.o
.PHONY : object.o

# target to build an object file
object.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/object.cpp.o
.PHONY : object.cpp.o

object.i: object.cpp.i
.PHONY : object.i

# target to preprocess a source file
object.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/object.cpp.i
.PHONY : object.cpp.i

object.s: object.cpp.s
.PHONY : object.s

# target to generate assembly for a file
object.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/object.cpp.s
.PHONY : object.cpp.s

objectInfo.o: objectInfo.cpp.o
.PHONY : objectInfo.o

# target to build an object file
objectInfo.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectInfo.cpp.o
.PHONY : objectInfo.cpp.o

objectInfo.i: objectInfo.cpp.i
.PHONY : objectInfo.i

# target to preprocess a source file
objectInfo.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectInfo.cpp.i
.PHONY : objectInfo.cpp.i

objectInfo.s: objectInfo.cpp.s
.PHONY : objectInfo.s

# target to generate assembly for a file
objectInfo.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectInfo.cpp.s
.PHONY : objectInfo.cpp.s

objectList.o: objectList.cpp.o
.PHONY : objectList.o

# target to build an object file
objectList.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectList.cpp.o
.PHONY : objectList.cpp.o

objectList.i: objectList.cpp.i
.PHONY : objectList.i

# target to preprocess a source file
objectList.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectList.cpp.i
.PHONY : objectList.cpp.i

objectList.s: objectList.cpp.s
.PHONY : objectList.s

# target to generate assembly for a file
objectList.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/objectList.cpp.s
.PHONY : objectList.cpp.s

openGLgraphics.o: openGLgraphics.cpp.o
.PHONY : openGLgraphics.o

# target to build an object file
openGLgraphics.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/openGLgraphics.cpp.o
.PHONY : openGLgraphics.cpp.o

openGLgraphics.i: openGLgraphics.cpp.i
.PHONY : openGLgraphics.i

# target to preprocess a source file
openGLgraphics.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/openGLgraphics.cpp.i
.PHONY : openGLgraphics.cpp.i

openGLgraphics.s: openGLgraphics.cpp.s
.PHONY : openGLgraphics.s

# target to generate assembly for a file
openGLgraphics.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/openGLgraphics.cpp.s
.PHONY : openGLgraphics.cpp.s

particleExplosion.o: particleExplosion.cpp.o
.PHONY : particleExplosion.o

# target to build an object file
particleExplosion.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleExplosion.cpp.o
.PHONY : particleExplosion.cpp.o

particleExplosion.i: particleExplosion.cpp.i
.PHONY : particleExplosion.i

# target to preprocess a source file
particleExplosion.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleExplosion.cpp.i
.PHONY : particleExplosion.cpp.i

particleExplosion.s: particleExplosion.cpp.s
.PHONY : particleExplosion.s

# target to generate assembly for a file
particleExplosion.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleExplosion.cpp.s
.PHONY : particleExplosion.cpp.s

particleManager.o: particleManager.cpp.o
.PHONY : particleManager.o

# target to build an object file
particleManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleManager.cpp.o
.PHONY : particleManager.cpp.o

particleManager.i: particleManager.cpp.i
.PHONY : particleManager.i

# target to preprocess a source file
particleManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleManager.cpp.i
.PHONY : particleManager.cpp.i

particleManager.s: particleManager.cpp.s
.PHONY : particleManager.s

# target to generate assembly for a file
particleManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/particleManager.cpp.s
.PHONY : particleManager.cpp.s

plane.o: plane.cpp.o
.PHONY : plane.o

# target to build an object file
plane.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/plane.cpp.o
.PHONY : plane.cpp.o

plane.i: plane.cpp.i
.PHONY : plane.i

# target to preprocess a source file
plane.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/plane.cpp.i
.PHONY : plane.cpp.i

plane.s: plane.cpp.s
.PHONY : plane.s

# target to generate assembly for a file
plane.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/plane.cpp.s
.PHONY : plane.cpp.s

planeContrail.o: planeContrail.cpp.o
.PHONY : planeContrail.o

# target to build an object file
planeContrail.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeContrail.cpp.o
.PHONY : planeContrail.cpp.o

planeContrail.i: planeContrail.cpp.i
.PHONY : planeContrail.i

# target to preprocess a source file
planeContrail.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeContrail.cpp.i
.PHONY : planeContrail.cpp.i

planeContrail.s: planeContrail.cpp.s
.PHONY : planeContrail.s

# target to generate assembly for a file
planeContrail.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeContrail.cpp.s
.PHONY : planeContrail.cpp.s

planeEngines.o: planeEngines.cpp.o
.PHONY : planeEngines.o

# target to build an object file
planeEngines.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeEngines.cpp.o
.PHONY : planeEngines.cpp.o

planeEngines.i: planeEngines.cpp.i
.PHONY : planeEngines.i

# target to preprocess a source file
planeEngines.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeEngines.cpp.i
.PHONY : planeEngines.cpp.i

planeEngines.s: planeEngines.cpp.s
.PHONY : planeEngines.s

# target to generate assembly for a file
planeEngines.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/planeEngines.cpp.s
.PHONY : planeEngines.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/player.cpp.s
.PHONY : player.cpp.s

random.o: random.cpp.o
.PHONY : random.o

# target to build an object file
random.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/random.cpp.o
.PHONY : random.cpp.o

random.i: random.cpp.i
.PHONY : random.i

# target to preprocess a source file
random.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/random.cpp.i
.PHONY : random.cpp.i

random.s: random.cpp.s
.PHONY : random.s

# target to generate assembly for a file
random.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/random.cpp.s
.PHONY : random.cpp.s

sceneManager.o: sceneManager.cpp.o
.PHONY : sceneManager.o

# target to build an object file
sceneManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/sceneManager.cpp.o
.PHONY : sceneManager.cpp.o

sceneManager.i: sceneManager.cpp.i
.PHONY : sceneManager.i

# target to preprocess a source file
sceneManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/sceneManager.cpp.i
.PHONY : sceneManager.cpp.i

sceneManager.s: sceneManager.cpp.s
.PHONY : sceneManager.s

# target to generate assembly for a file
sceneManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/sceneManager.cpp.s
.PHONY : sceneManager.cpp.s

settings.o: settings.cpp.o
.PHONY : settings.o

# target to build an object file
settings.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/settings.cpp.o
.PHONY : settings.cpp.o

settings.i: settings.cpp.i
.PHONY : settings.i

# target to preprocess a source file
settings.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/settings.cpp.i
.PHONY : settings.cpp.i

settings.s: settings.cpp.s
.PHONY : settings.s

# target to generate assembly for a file
settings.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/settings.cpp.s
.PHONY : settings.cpp.s

ship.o: ship.cpp.o
.PHONY : ship.o

# target to build an object file
ship.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ship.cpp.o
.PHONY : ship.cpp.o

ship.i: ship.cpp.i
.PHONY : ship.i

# target to preprocess a source file
ship.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ship.cpp.i
.PHONY : ship.cpp.i

ship.s: ship.cpp.s
.PHONY : ship.s

# target to generate assembly for a file
ship.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/ship.cpp.s
.PHONY : ship.cpp.s

smokeTrail.o: smokeTrail.cpp.o
.PHONY : smokeTrail.o

# target to build an object file
smokeTrail.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/smokeTrail.cpp.o
.PHONY : smokeTrail.cpp.o

smokeTrail.i: smokeTrail.cpp.i
.PHONY : smokeTrail.i

# target to preprocess a source file
smokeTrail.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/smokeTrail.cpp.i
.PHONY : smokeTrail.cpp.i

smokeTrail.s: smokeTrail.cpp.s
.PHONY : smokeTrail.s

# target to generate assembly for a file
smokeTrail.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/smokeTrail.cpp.s
.PHONY : smokeTrail.cpp.s

soundManager.o: soundManager.cpp.o
.PHONY : soundManager.o

# target to build an object file
soundManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/soundManager.cpp.o
.PHONY : soundManager.cpp.o

soundManager.i: soundManager.cpp.i
.PHONY : soundManager.i

# target to preprocess a source file
soundManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/soundManager.cpp.i
.PHONY : soundManager.cpp.i

soundManager.s: soundManager.cpp.s
.PHONY : soundManager.s

# target to generate assembly for a file
soundManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/soundManager.cpp.s
.PHONY : soundManager.cpp.s

splash.o: splash.cpp.o
.PHONY : splash.o

# target to build an object file
splash.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash.cpp.o
.PHONY : splash.cpp.o

splash.i: splash.cpp.i
.PHONY : splash.i

# target to preprocess a source file
splash.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash.cpp.i
.PHONY : splash.cpp.i

splash.s: splash.cpp.s
.PHONY : splash.s

# target to generate assembly for a file
splash.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash.cpp.s
.PHONY : splash.cpp.s

splash2.o: splash2.cpp.o
.PHONY : splash2.o

# target to build an object file
splash2.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash2.cpp.o
.PHONY : splash2.cpp.o

splash2.i: splash2.cpp.i
.PHONY : splash2.i

# target to preprocess a source file
splash2.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash2.cpp.i
.PHONY : splash2.cpp.i

splash2.s: splash2.cpp.s
.PHONY : splash2.s

# target to generate assembly for a file
splash2.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splash2.cpp.s
.PHONY : splash2.cpp.s

splitScreen.o: splitScreen.cpp.o
.PHONY : splitScreen.o

# target to build an object file
splitScreen.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splitScreen.cpp.o
.PHONY : splitScreen.cpp.o

splitScreen.i: splitScreen.cpp.i
.PHONY : splitScreen.i

# target to preprocess a source file
splitScreen.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splitScreen.cpp.i
.PHONY : splitScreen.cpp.i

splitScreen.s: splitScreen.cpp.s
.PHONY : splitScreen.s

# target to generate assembly for a file
splitScreen.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/splitScreen.cpp.s
.PHONY : splitScreen.cpp.s

terrain.o: terrain.cpp.o
.PHONY : terrain.o

# target to build an object file
terrain.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/terrain.cpp.o
.PHONY : terrain.cpp.o

terrain.i: terrain.cpp.i
.PHONY : terrain.i

# target to preprocess a source file
terrain.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/terrain.cpp.i
.PHONY : terrain.cpp.i

terrain.s: terrain.cpp.s
.PHONY : terrain.s

# target to generate assembly for a file
terrain.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/terrain.cpp.s
.PHONY : terrain.cpp.s

time.o: time.cpp.o
.PHONY : time.o

# target to build an object file
time.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/time.cpp.o
.PHONY : time.cpp.o

time.i: time.cpp.i
.PHONY : time.i

# target to preprocess a source file
time.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/time.cpp.i
.PHONY : time.cpp.i

time.s: time.cpp.s
.PHONY : time.s

# target to generate assembly for a file
time.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/time.cpp.s
.PHONY : time.cpp.s

tracer.o: tracer.cpp.o
.PHONY : tracer.o

# target to build an object file
tracer.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/tracer.cpp.o
.PHONY : tracer.cpp.o

tracer.i: tracer.cpp.i
.PHONY : tracer.i

# target to preprocess a source file
tracer.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/tracer.cpp.i
.PHONY : tracer.cpp.i

tracer.s: tracer.cpp.s
.PHONY : tracer.s

# target to generate assembly for a file
tracer.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/tracer.cpp.s
.PHONY : tracer.cpp.s

worldManager.o: worldManager.cpp.o
.PHONY : worldManager.o

# target to build an object file
worldManager.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/worldManager.cpp.o
.PHONY : worldManager.cpp.o

worldManager.i: worldManager.cpp.i
.PHONY : worldManager.i

# target to preprocess a source file
worldManager.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/worldManager.cpp.i
.PHONY : worldManager.cpp.i

worldManager.s: worldManager.cpp.s
.PHONY : worldManager.s

# target to generate assembly for a file
worldManager.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/worldManager.cpp.s
.PHONY : worldManager.cpp.s

xml/tinyxml2.o: xml/tinyxml2.cpp.o
.PHONY : xml/tinyxml2.o

# target to build an object file
xml/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/xml/tinyxml2.cpp.o
.PHONY : xml/tinyxml2.cpp.o

xml/tinyxml2.i: xml/tinyxml2.cpp.i
.PHONY : xml/tinyxml2.i

# target to preprocess a source file
xml/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/xml/tinyxml2.cpp.i
.PHONY : xml/tinyxml2.cpp.i

xml/tinyxml2.s: xml/tinyxml2.cpp.s
.PHONY : xml/tinyxml2.s

# target to generate assembly for a file
xml/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/FighterPilot.dir/build.make CMakeFiles/FighterPilot.dir/xml/tinyxml2.cpp.s
.PHONY : xml/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... FighterPilot"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aaGun.o"
	@echo "... aaGun.i"
	@echo "... aaGun.s"
	@echo "... angle.o"
	@echo "... angle.i"
	@echo "... angle.s"
	@echo "... assetLoader.o"
	@echo "... assetLoader.i"
	@echo "... assetLoader.s"
	@echo "... blackSmoke.o"
	@echo "... blackSmoke.i"
	@echo "... blackSmoke.s"
	@echo "... bomb.o"
	@echo "... bomb.i"
	@echo "... bomb.s"
	@echo "... bullet.o"
	@echo "... bullet.i"
	@echo "... bullet.s"
	@echo "... bulletEffect.o"
	@echo "... bulletEffect.i"
	@echo "... bulletEffect.s"
	@echo "... campaign.o"
	@echo "... campaign.i"
	@echo "... campaign.s"
	@echo "... collide.o"
	@echo "... collide.i"
	@echo "... collide.s"
	@echo "... contrail.o"
	@echo "... contrail.i"
	@echo "... contrail.s"
	@echo "... contrailSmall.o"
	@echo "... contrailSmall.i"
	@echo "... contrailSmall.s"
	@echo "... controlManager.o"
	@echo "... controlManager.i"
	@echo "... controlManager.s"
	@echo "... dataManager.o"
	@echo "... dataManager.i"
	@echo "... dataManager.s"
	@echo "... debrisSmokeTrail.o"
	@echo "... debrisSmokeTrail.i"
	@echo "... debrisSmokeTrail.s"
	@echo "... debugBreak.o"
	@echo "... debugBreak.i"
	@echo "... debugBreak.s"
	@echo "... definitions.o"
	@echo "... definitions.i"
	@echo "... definitions.s"
	@echo "... dogFight.o"
	@echo "... dogFight.i"
	@echo "... dogFight.s"
	@echo "... engine.o"
	@echo "... engine.i"
	@echo "... engine.s"
	@echo "... ephemeris.o"
	@echo "... ephemeris.i"
	@echo "... ephemeris.s"
	@echo "... explosionFlash.o"
	@echo "... explosionFlash.i"
	@echo "... explosionFlash.s"
	@echo "... explosionFlash2.o"
	@echo "... explosionFlash2.i"
	@echo "... explosionFlash2.s"
	@echo "... explosionSmoke.o"
	@echo "... explosionSmoke.i"
	@echo "... explosionSmoke.s"
	@echo "... explosionSparks.o"
	@echo "... explosionSparks.i"
	@echo "... explosionSparks.s"
	@echo "... fileManager.o"
	@echo "... fileManager.i"
	@echo "... fileManager.s"
	@echo "... fireball.o"
	@echo "... fireball.i"
	@echo "... fireball.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... glew.o"
	@echo "... glew.i"
	@echo "... glew.s"
	@echo "... graphicsManager.o"
	@echo "... graphicsManager.i"
	@echo "... graphicsManager.s"
	@echo "... groundExplosionFlash.o"
	@echo "... groundExplosionFlash.i"
	@echo "... groundExplosionFlash.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... level.o"
	@echo "... level.i"
	@echo "... level.s"
	@echo "... levelEditor.o"
	@echo "... levelEditor.i"
	@echo "... levelEditor.s"
	@echo "... menuScreen.o"
	@echo "... menuScreen.i"
	@echo "... menuScreen.s"
	@echo "... menus.o"
	@echo "... menus.i"
	@echo "... menus.s"
	@echo "... missile.o"
	@echo "... missile.i"
	@echo "... missile.s"
	@echo "... object.o"
	@echo "... object.i"
	@echo "... object.s"
	@echo "... objectInfo.o"
	@echo "... objectInfo.i"
	@echo "... objectInfo.s"
	@echo "... objectList.o"
	@echo "... objectList.i"
	@echo "... objectList.s"
	@echo "... openGLgraphics.o"
	@echo "... openGLgraphics.i"
	@echo "... openGLgraphics.s"
	@echo "... particleExplosion.o"
	@echo "... particleExplosion.i"
	@echo "... particleExplosion.s"
	@echo "... particleManager.o"
	@echo "... particleManager.i"
	@echo "... particleManager.s"
	@echo "... plane.o"
	@echo "... plane.i"
	@echo "... plane.s"
	@echo "... planeContrail.o"
	@echo "... planeContrail.i"
	@echo "... planeContrail.s"
	@echo "... planeEngines.o"
	@echo "... planeEngines.i"
	@echo "... planeEngines.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... sceneManager.o"
	@echo "... sceneManager.i"
	@echo "... sceneManager.s"
	@echo "... settings.o"
	@echo "... settings.i"
	@echo "... settings.s"
	@echo "... ship.o"
	@echo "... ship.i"
	@echo "... ship.s"
	@echo "... smokeTrail.o"
	@echo "... smokeTrail.i"
	@echo "... smokeTrail.s"
	@echo "... soundManager.o"
	@echo "... soundManager.i"
	@echo "... soundManager.s"
	@echo "... splash.o"
	@echo "... splash.i"
	@echo "... splash.s"
	@echo "... splash2.o"
	@echo "... splash2.i"
	@echo "... splash2.s"
	@echo "... splitScreen.o"
	@echo "... splitScreen.i"
	@echo "... splitScreen.s"
	@echo "... terrain.o"
	@echo "... terrain.i"
	@echo "... terrain.s"
	@echo "... time.o"
	@echo "... time.i"
	@echo "... time.s"
	@echo "... tracer.o"
	@echo "... tracer.i"
	@echo "... tracer.s"
	@echo "... worldManager.o"
	@echo "... worldManager.i"
	@echo "... worldManager.s"
	@echo "... xml/tinyxml2.o"
	@echo "... xml/tinyxml2.i"
	@echo "... xml/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

